CC=gcc


string-parsing: string-parsing.c ../include/parser.h ../include/command.h ../include/stack_arena.h ../src/parser.c
	$(CC) -g string-parsing.c ../src/parser.c ../src/stack_arena.c -o String-parsing
